---
- hosts: "{{ target | default('localhost') }}"
  gather_facts: yes
  ignore_errors: yes
  tasks:
  - name : install kubectl
    community.general.homebrew:
      name: kubectl
      state: present
  - name : install terraform 
    community.general.homebrew:
      name: terraform
      state: present
  - name: install helm3
    community.general.homebrew:
      name: helm
      state: present
  - name: download gcloud macos 64 bit 
    get_url:
      url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-317.0.0-darwin-x86_64.tar.gz
      dest: /tmp
      checksum: sha256:3873c60474754192371d4b7d801848d148da620640721c08b757644b47daab4c
  - name : install tar utility 
    community.general.homebrew:
      name: gnu-tar 
      state: present 
  - name : extract tar 
    unarchive:
      src: /tmp/google-cloud-sdk-317.0.0-darwin-x86_64.tar.gz
      dest: /tmp
