---
- hosts: "{{ target | default('localhost') }}"
  gather_facts: yes
  ignore_errors: yes
  tasks:
  - name : install kubectl
    community.general.homebrew:
      name: kubectl
      state: present
  - name : install terraform 
    community.general.homebrew:
      name: terraform
      state: present
  - name: install helm3
    community.general.homebrew:
      name: helm
      state: present
  - name: install gcloud utility
    community.general.homebrew:
      name: google-cloud-sdk
      state: present
 